<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        ClasseMere
 */
require_once('/../classeBase.php');

class Ami extends ClasseMere {

	/**
	 *
	 * @var timestamp
	 * @access private
	 */
	private  $date_demande;

	/**
	 *
	 * @var timestamp
	 * @access private
	 */
	private  $date_ajout;

	/**
	 *
	 * @var timestamp
	 * @access private
	 */
	private  $date_refus;

	/**
	 *
	 * @var Coach
	 * @access private
	 */
	private  $coachAmi;


	/**
	 * @access public
	 * @param array $donnees
	 * @return void
	 */
	public final  function __construct($donnees) {
		$this->_coachAmi = new Coach($donnees);
		parent::hydrate($donnees);
	}


		/**
		 * @access public
		 * @return timestamp
		 */
		public final  function dateDemande() {
			return $this->_date_demande;
		}


	/**
	 * @access public
	 * @return timestamp
	 */
	public final  function dateAjout() {
		return $this->_date_ajout;
	}


	/**
	 * @access public
	 * @return timestamp
	 */
	public final  function dateRefus() {
		return $this->_date_refus;
	}


		/**
		 * @access public
		 * @return Coach
		 */
		public final  function coachAmi() {
			return $this->_coachAmi;
		}

			/**
			 * @access public
			 * @param timestamp $dateDemande
			 * @return void
			 */
			public final  function setDate_demande($dateDemande) {
				$this->_date_demande = $dateDemande;
			}

	/**
	 * @access public
	 * @param timestamp $dateAjout
	 * @return void
	 */
	public final  function setDate_ajout($dateAjout) {
		$this->_date_ajout = $dateAjout;
	}


	/**
	 * @access public
	 * @param timestamp $dateRefus
	 * @return void
	 */
	public final  function setDate_refus($dateRefus) {
		$this->_date_refus = $dateRefus;
	}
}
?>
