<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        ClasseMere
 */
require_once('/../ClasseBase.php');

class Ami extends ClasseMere {

	/**
	 *
	 * @var timestamp
	 * @access private
	 */
	private  $date_ajout;

	/**
	 *
	 * @var timestamp
	 * @access private
	 */
	private  $date_refus;

	/**
	 *
	 * @var Coach
	 * @access private
	 */
	private  $coachDemandeur;

	/**
	 *
	 * @var Coach
	 * @access private
	 */
	private  $coachDemande;


	/**
	 * @access public
	 * @param array $donnees
	 * @return void
	 */

	public final  function __construct($donnees) {

	}


	/**
	 * @access public
	 * @return timestamp
	 */

	public final  function dateAjout() {

	}


	/**
	 * @access public
	 * @return timestamp
	 */

	public final  function dateRefus() {

	}


	/**
	 * @access public
	 * @param timestamp $dateAjout
	 * @return void
	 */

	public final  function setDateAjout(timestamp $dateAjout) {

	}


	/**
	 * @access public
	 * @param timestamp $dateRefus
	 * @return void
	 */

	public final  function setDateRefus(timestamp $dateRefus) {

	}


	/**
	 * @access public
	 * @return Coach
	 */

	public final  function coachDemandeur() {

	}


	/**
	 * @access public
	 * @return Coach
	 */

	public final  function coachDemande() {

	}


	/**
	 * @access public
	 * @param string $id
	 * @return void
	 */

	public final  function setIdCoachDemandeur($id) {

	}


	/**
	 * @access public
	 * @param string $id
	 * @return void
	 */

	public final  function setIdCoachDemande($id) {

	}


}
?>
