<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class AmiManager {

	/**
	 *
	 * @var PDO
	 * @access private
	 */
	private  $bdd;


	/**
	 * @access public
	 * @param PDO $bdd
	 * @return void
	 */
	public final  function __construct(PDO $bdd) {
		$this->setDb($bdd);
	}


	/**
	 * @access public
	 * @param Coach $coachDemandeur
	 * @param $idAmi
	 * @return void
	 */
	public final  function creerAmi(Coach $coachDemandeur, $idAmi) {
		$q = $this->_bdd->prepare('INSERT INTO ami(id_coach, id_coach_ami) VALUES(:id, :idAmi)');
    $q->bindValue(':id', $coachDemandeur->id());
    $q->bindValue(':idAmi', $idAmi);

    $q->execute();
	}

	public function setDb(PDO $bdd)
  {
    $this->_bdd = $bdd;
  }
}
?>
