<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class AmiManager {

	/**
	 *
	 * @var PDO
	 * @access private
	 */
	private  $bdd;


	/**
	 * @access public
	 * @param PDO $bdd
	 * @return void
	 */
	public final  function __construct(PDO $bdd) {
		$this->setDb($bdd);
	}


	/**
	 * @access public
	 * @param Coach $coachDemandeur
	 * @param $idAmi
	 * @return void
	 */
	public final  function creerAmi(Coach $coachDemandeur, $idAmi) {
		$q = $this->_bdd->prepare('INSERT INTO ami(id_coach, id_coach_ami) VALUES(:id, :idAmi)');
    $q->bindValue(':id', $coachDemandeur->id());
    $q->bindValue(':idAmi', $idAmi);

    $q->execute();
	}

	public function findAmisByIdCoach($idCoach)
	{
		$amis = [];

		$q = $this->_bdd->prepare('SELECT a.date_ajout, a.date_refus, c.id, c.nom, c.code_postal
						FROM ami a
						INNER JOIN coach c ON a.id_coach_ami = c.id
						WHERE (a.id_coach = :id OR a.id_coach_ami = :id2)
						AND a.date_ajout IS NOT NULL AND a.date_refus IS NULL');
		$q->execute([':id' => $idCoach, ':id2' => $idCoach]);

		while ($donnees = $q->fetch(PDO::FETCH_ASSOC))
		{
			$amis[] = new Ami($donnees);
		}
		$q->closeCursor();

		return $amis;
	}

	public function compterNbDemandeAjout($idCoach)
	{
		$q = $this->_bdd->prepare('SELECT COUNT(*) as nbDemandeAjout FROM ami WHERE id_coach_ami = :id
						AND date_ajout IS NULL and date_refus IS NULL');
		$q->execute([':id' => $idCoach]);

		$donnees = $q->fetch(PDO::FETCH_ASSOC);
		$q->closeCursor();

		return $donnees['nbDemandeAjout'];
	}

	public function setDb(PDO $bdd)
  {
    $this->_bdd = $bdd;
  }
}
?>
