<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
//require 'ami.php';

class AmiManager {

	/**
	 *
	 * @var PDO
	 * @access private
	 */
	private  $bdd;


	/**
	 * @access public
	 * @param PDO $bdd
	 * @return void
	 */
	public final function __construct(PDO $bdd) {
		$this->setDb($bdd);
	}


	/**
	 * @access public
	 * @param Coach $coachDemandeur
	 * @param $idAmi
	 * @return void
	 */
	public final function creerAmi(Coach $coachDemandeur, $idAmi) {
		$q = $this->_bdd->prepare('INSERT INTO ami(id_coach, id_coach_ami, date_demande) VALUES(:id, :idAmi, NOW())');
    $q->bindValue(':id', $coachDemandeur->id());
    $q->bindValue(':idAmi', $idAmi);

    $q->execute();
	}

	public final function accepterAmi(Coach $coach, $idCoachDemandeur) {
		$q = $this->_bdd->prepare('UPDATE ami SET date_ajout = NOW() WHERE id_coach = :id AND id_coach_ami = :idAmi');
    $q->bindValue(':id', $idCoachDemandeur);
    $q->bindValue(':idAmi', $coach->id());

    $q->execute();
	}

	public final function refuserAmi(Coach $coach, $idCoachDemandeur) {
		$q = $this->_bdd->prepare('UPDATE ami SET date_refus = NOW() WHERE id_coach = :id AND id_coach_ami = :idAmi');
		$q->bindValue(':id', $idCoachDemandeur);
		$q->bindValue(':idAmi', $coach->id());

		$q->execute();
	}

	public final function supprimerAmi(Coach $coach, $idCoachAmi) {
		$q = $this->_bdd->prepare('UPDATE ami SET date_refus = NOW()
				WHERE (id_coach = :id1 AND id_coach_ami = :idAmi1) OR (id_coach = :idAmi2 AND id_coach_ami = :id2)');
		$q->bindValue(':id1', $idCoachAmi);
		$q->bindValue(':idAmi1', $coach->id());
		$q->bindValue(':id2', $coach->id());
		$q->bindValue(':idAmi2', $idCoachAmi);

		$q->execute();
	}

	public function findAmisByIdCoach($idCoach)
	{
		$amis = [];

		// Amis demandés
		$q = $this->_bdd->prepare('SELECT a.date_ajout, a.date_refus, c.id, c.nom, c.code_postal
						FROM ami a
						INNER JOIN coach c ON a.id_coach_ami = c.id
						WHERE a.id_coach = :id
						AND a.date_ajout IS NOT NULL AND a.date_refus IS NULL');
		$q->execute([':id' => $idCoach]);

		while ($donnees = $q->fetch(PDO::FETCH_ASSOC))
		{
			$amis[] = new Ami($donnees);
		}
		$q->closeCursor();

		// Demandes d'ajout
		$q = $this->_bdd->prepare('SELECT a.date_ajout, a.date_refus, c.id, c.nom, c.code_postal
						FROM ami a
						INNER JOIN coach c ON a.id_coach = c.id
						WHERE a.id_coach_ami = :id
						AND a.date_ajout IS NOT NULL AND a.date_refus IS NULL');
		$q->execute([':id' => $idCoach]);

		while ($donnees = $q->fetch(PDO::FETCH_ASSOC))
		{
			$amis[] = new Ami($donnees);
		}
		$q->closeCursor();

		return $amis;
	}

	public function findDemandeAjoutByIdCoach($idCoach)
	{
		$amis = [];

		$q = $this->_bdd->prepare('SELECT a.date_demande, c.id, c.nom, c.code_postal
						FROM ami a
						INNER JOIN coach c ON a.id_coach = c.id
						WHERE a.id_coach_ami = :id
						AND a.date_ajout IS NULL AND a.date_refus IS NULL');
		$q->execute([':id' => $idCoach]);

		while ($donnees = $q->fetch(PDO::FETCH_ASSOC))
		{
			$amis[] = new Ami($donnees);
		}
		$q->closeCursor();

		return $amis;
	}

	public function findAmiDemandeEnCoursByIdCoach($idCoach)
	{
		$amis = [];

		$q = $this->_bdd->prepare('SELECT a.date_demande, c.id, c.nom, c.code_postal
						FROM ami a
						INNER JOIN coach c ON a.id_coach_ami = c.id
						WHERE a.id_coach = :id
						AND a.date_ajout IS NULL AND a.date_refus IS NULL');
		$q->execute([':id' => $idCoach]);

		while ($donnees = $q->fetch(PDO::FETCH_ASSOC))
		{
			$amis[] = new Ami($donnees);
		}
		$q->closeCursor();

		return $amis;
	}

	public function compterNbDemandeAjout($idCoach)
	{
		$q = $this->_bdd->prepare('SELECT COUNT(*) as nbDemandeAjout FROM ami WHERE id_coach_ami = :id
						AND date_ajout IS NULL and date_refus IS NULL');
		$q->execute([':id' => $idCoach]);

		$donnees = $q->fetch(PDO::FETCH_ASSOC);
		$q->closeCursor();

		return $donnees['nbDemandeAjout'];
	}

	public function setDb(PDO $bdd)
  {
    $this->_bdd = $bdd;
  }
}
?>
