<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ConfrereManager {

	/**
	 *
	 * @var PDO
	 * @access private
	 */
	private  $bdd;


	/**
	 * @access public
	 * @param PDO $bdd
	 * @return void
	 */
	public final function __construct(PDO $bdd) {
		$this->setDb($bdd);
	}


	/**
	 * @access public
	 * @param Coach $coachDemandeur
	 * @param $idConfrere
	 * @return void
	 */
	public final function creerConfrere(Coach $coachDemandeur, $idConfrere) {
		$q = $this->_bdd->prepare('INSERT INTO confrere(id_coach, id_coach_confrere, date_debut) VALUES(:id, :idConfrere, NOW())');
    $q->bindValue(':id', $coachDemandeur->id());
    $q->bindValue(':idConfrere', $idConfrere);

    $q->execute();
	}

	public final function supprimerConfrere(Coach $coach, $idCoachConfrere) {
		$q = $this->_bdd->prepare('DELETE FROM confrere
				WHERE id_coach = :id AND id_coach_confrere = :idConfrere');
		$q->bindValue(':id', $coach->id());
		$q->bindValue(':idConfrere', $idCoachConfrere);

		$q->execute();
	}

	public function findConfreresByIdCoach($idCoach)
	{
		$confreres = [];

		// Confreres demandés
		$q = $this->_bdd->prepare('SELECT cf.date_debut, c.id, c.nom, c.code_postal
						FROM confrere cf
						INNER JOIN coach c ON cf.id_coach_confrere = c.id
						WHERE cf.id_coach = :id');
		$q->execute([':id' => $idCoach]);

		while ($donnees = $q->fetch(PDO::FETCH_ASSOC))
		{
			$confreres[] = new Confrere($donnees);
		}
		$q->closeCursor();

		return $confreres;
	}

	public function setDb(PDO $bdd)
  {
    $this->_bdd = $bdd;
  }
}
?>
