<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        ClasseMere
 */
require_once(__DIR__ . '/../classeBase.php');

class Confrere extends ClasseBase {

	/**
	 *
	 * @var timestamp
	 * @access private
	 */
	private  $date_debut;

	/**
	 *
	 * @var Coach
	 * @access private
	 */
	private  $coachConfrere;


	/**
	 * @access public
	 * @param array $donnees
	 * @return void
	 */
	public final  function __construct($donnees) {
		$this->_coachConfrere = new Coach($donnees);
		parent::hydrate($donnees);
	}


		/**
		 * @access public
		 * @return timestamp
		 */
		public final  function dateDebut() {
			return $this->_date_debut;
		}

		/**
			* @access public
			* @param timestamp $dateDebut
			* @return void
			*/
		public final  function setDate_debut($dateDebut) {
			$this->_date_debut = $dateDebut;
		}


		/**
			* @access public
			* @return Coach
		  */
		public final  function coachConfrere() {
			return $this->_coachConfrere;
		}
}
?>
